# Build stage
FROM maven:3-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

# Run stage
FROM openjdk:17.0-jdk-slim
COPY --from=build /target/Portfolio-0.0.1-SNAPSHOT.jar Portfolio.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "Portfolio.jar" ]
